webshopping/lolshopping/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('cart/', views.cart, name = 'cart'),
    path('checkout/', views.checkout, name = 'checkout'),
    path('confirmation/', views.confirmation, name = 'confirmation'),
    path('update_item/', views.updateItem, name = 'update_Item'),
    path('process_order/', views.processOrder, name = 'process_order'),
    # path('addUserInfoForm/',views.addUserInfoForm, name='addUserInfoForm'),
    path('registerUser/',views.registerUserpage, name='registerUserpage'),
    path('login/',views.LoginPage, name='LoginPage'),
    path('profile/',views.userProfile, name='Profile'),
    path('logout/',views.LogoutPage, name='LogoutPage'),
]

webshopping/webshopping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lolshopping.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webshopping/lolshopping/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
import os


class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have a username")

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            )

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user



class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name = 'email', max_length = 60, unique=True)
    username = models.CharField(max_length = 30, unique=True)
    password = None
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    new_salt = models.CharField(max_length = 100, null=True)
    new_hash_value = models.CharField(max_length = 200, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = MyAccountManager()

    def __str__(self):
        return self.email


    def has_perm(self,perm,obj=None):
        return self.is_admin

    def has_module_perms(self, app_lable):
        return True






class Champions(models.Model):

    name = models.CharField(max_length=30)
    role = models.CharField(max_length=30)
    price = models.DecimalField(decimal_places = 0, max_digits=2)
    picture = models.ImageField(upload_to='champic/')
    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.picture.url
        except:
            url = ''
        return url

class Customer(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    # Personal information
    full_name = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)
    phone_number = models.DecimalField(decimal_places=0, max_digits=12, null=True)
    #shipping address
    address_line_1 = models.CharField(max_length=100, null=True)
    address_line_2 = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    postal_code = models.DecimalField(decimal_places=0, max_digits=10, null=True)


    def __str__(self):
        return self.name

class Order(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, blank=True,null=True)
    complete = models.BooleanField(default=False,null=True,blank=False)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Champions,on_delete=models.SET_NULL, blank=True,null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL, blank=True,null=True)
    quantity = models.IntegerField(default=0, null=True,blank=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

webshopping/lolshopping/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.forms import ModelForm
import os
import hashlib

from .models import Account, Customer

class RegistrationForm(forms.ModelForm):
    email = forms.EmailField(max_length=60, help_text='Required. Add a valid email address',)
    error_messages = {
        'password_mismatch': ("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=("Enter the same password as above, for verification."))

    class Meta:
        model = Account
        fields = ("email", "username", "password1", "password2")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        instance = super(RegistrationForm,self).save(commit=False)
        raw_password = self.cleaned_data.get('password1')
        salt = os.urandom(5)
        instance.new_salt = str(salt)
        new_hash_val = hashlib.pbkdf2_hmac('sha256', raw_password.encode(), str.encode(instance.new_salt), 100000)
        instance.new_hash_value = new_hash_val.hex()



        if commit:
            instance.save()
        return instance

class AccountAuthenticationForm(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            try:
                user = Account.objects.get(email=email)
            except Account.DoesNotExist:
                raise forms.ValidationError("Invalid login")
            # if not authenticate(email=email):
            #     print(email)
            #     raise forms.ValidationError("Invalid login")


class UserProfileForm(ModelForm):
    address_line_2 = forms.CharField(required=False)

    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user','name','email']

webshopping/lolshopping/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
from .models import *
from .forms import RegistrationForm, AccountAuthenticationForm, UserProfileForm
from django.contrib.auth import login, authenticate, logout
from .filters import ChampionsFilter
from django.contrib import messages
import psycopg2
import hashlib
import os
from django.contrib.auth import get_user_model
from .utils import cookieCart
UserModel = get_user_model()



def registerUserpage(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            email = form.cleaned_data.get('email')
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')


            user_from_usermodel = UserModel._default_manager.get_by_natural_key(email)


            # hash_save = Account.objects.get(id = user_from_usermodel.id )
            # new_hash_val = hashlib.pbkdf2_hmac('sha256', raw_password.encode(), str.encode(user_from_usermodel.new_salt), 100000)
            # hash_save.new_hash_value = new_hash_val.hex()

            # hash_save.save()
            Customer.objects.create(
                user=user,
                name=user.username,
                email=user.email
                )


            login(request, user_from_usermodel)  #log the user in
            return redirect('home')

    context ={'form':form}
    return render(request,'design/registerUser.html',context)

def LoginPage(request):

    user = request.user
    if user.is_authenticated:
        return redirect("home")

    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
                email = request.POST['email']
                password = request.POST['password']
                user = UserModel._default_manager.get_by_natural_key(email)
                hash_value_from_DB = user.new_hash_value
                hash_value = hashlib.pbkdf2_hmac('sha256', password.encode(), str.encode(user.new_salt), 100000) #output hash value
                hash_value = hash_value.hex()
                if hash_value == hash_value_from_DB:

                    login(request, user)
                    return redirect("home")

    else:
        form = AccountAuthenticationForm()

    context={'form':form}
    return render(request, 'design/login.html', context)


def userProfile(request):
    customer = request.user.customer
    form = UserProfileForm(instance = customer)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance = customer)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('Profile')

    context={'form':form}
    return render(request,'design/userProfile.html', context)

def LogoutPage(request):
    logout(request)
    return redirect('home')

def home(request):

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items

    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0}
        cartItems = order['get_cart_items']


    champ = Champions.objects.all().order_by('name')
    myFilter = ChampionsFilter(request.GET, queryset=champ)
    if request.GET.get('price') == 'LTH':
        champ = Champions.objects.all().order_by('price','name')
        # myFilter = ChampionsFilter(request.GET, queryset=champ)
        # champ = myFilter.qs

    elif request.GET.get('price') == 'HTL':
        champ = Champions.objects.all().order_by('-price','name')
        # myFilter = ChampionsFilter(request.GET, queryset=champ)
        # champ = myFilter.qs

    myFilter = ChampionsFilter(request.GET, queryset=champ)
    champ = myFilter.qs

    context = {'all':champ, 'myFilter':myFilter,'cartItems':cartItems,}
    return render(request,'design/home.html',context)
# Create your views here.

def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        cookieData = cookieCart(request)
        cartItems = cookieData['cartItems']
        order = cookieData['order']
        items = cookieData['items']


    context = {'items':items, 'order':order,'cartItems':cartItems}

    return render(request, 'design/cart.html', context)

def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0}
        cartItems = order['get_cart_items']
    context = {'items':items, 'order':order,'cartItems':cartItems}

    return render(request, 'design/checkout.html', context)

def confirmation(request):
    context = {}
    return render(request, 'design/confirmation.html', context)

def updateItem(request):
    data = json.loads(request.body)
    championId = data['championId']
    action = data['action']

    print('Action:', action)
    print('championId:', championId)



    customer = request.user.customer
    product = Champions.objects.get(id=championId)

    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity +1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity -1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()
    return JsonResponse('item was added', safe=False)

def processOrder(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

        order.complete=True
        order.save()
    else:
        print("user is not logged in")
    return JsonResponse('ORDER COMPLETE', safe=False)

webshopping/lolshopping/templates/design/cart.html
{% extends 'design/main.html' %}
{% load static %}
{% block content %}
    <title>Cart</title>
    <h1>Your Cart</h1>
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element-cart">

                <a  class="btn btn-outline-dark" href="{% url 'home' %}">&#x2190; Continue Shopping</a>

                <br>
                <br>

                <table class="table">

                    <tr>
                        <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                        <th><h5>Total: <strong>${{order.get_cart_total}}</strong></h5></th>
                        <th>
                            <a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
                        </th>
                    </tr>

                </table>

            </div>

            <br>

            <div class="box-element-cart">

                <div class="cart-row">
					<div style="flex:2"></div>
                    <div style="flex:1"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Role</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
                </div>
                {% for item in items %}
                <div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                    <div style="flex:1"><p>{{item.product.name}}</p></div>
                    <div style="flex:1"><p>{{item.product.role}}</p></div>
                    <div style="flex:1"><p>${{item.product.price}}</p></div>

					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
							<img data-product={{item.product.id}} data-action="remove"class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
                    </div>

                    <div style="flex:1">${{item.get_total}}</div>

				</div>
                {% endfor %}
            </div>

        </div>

    </div>
{% endblock content %}

webshopping/lolshopping/templates/design/checkout.html
{% extends 'design/main.html' %}
{% load static %}
{% block content %}
    <title>Checkout</title>
    <h1>Checkout</h1>

    <div class="row">

        <div class="col-lg-6">
            <div class="box-element-checkout" id="form-wrapper">
<!-- <<<<<<< final_branch -->

<!-- 				<form id="form" action = "{% url 'confirmation' %}" method = "get"> -->
                <!-- action="/addUserInfoForm/"> -->
                    <!-- {% csrf_token %} -->
<!-- ======= -->
				<form id="form" action = "{% url 'confirmation' %}" method = "get">
<!-- >>>>>>> master -->
                 <!-- action = "{% url 'confirmation' %}" method = "get"> -->

					<div id="user-info">

                        <p><h4>Enter Personal Information:</h4></p>

						<div class="form-field">
							<input required class="form-control" type="text" name="full_name" placeholder="Full name">
                        </div>

						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email">
                        </div>

                        <div class="form-field">
							<input required class="form-control" type="text" name="phone_number" placeholder="Phone number">
                        </div>

					</div>

					<div id="shipping-info">

                        <p><h4>Enter Shipping Address:</h4></p>

                        <div class="form-field">
							<input required class="form-control" type="text" name="address_line_1" placeholder="Address line 1">
                        </div>

                        <div class="form-field">
							<input class="form-control" type="text" name="address_line_2" placeholder="Address line 2">
                        </div>

						<div class="form-field">
							<input required class="form-control" type="text" name="city" placeholder="City">
                        </div>

						<div class="form-field">
							<input required class="form-control" type="text" name="state" placeholder="State">
                        </div>

						<div class="form-field">
							<input required class="form-control" type="text" name="postal_code" placeholder="Postal code">
                        </div>

                    </div>
                    <div id = 'change-info'>
                        <a href="{% url 'Profile' %}">change </a>
                    </div>
                    <div id="payment-info">

                        <p><h4>Enter Payment Method:</h4></p>

                        <div class="form-field-for-payment">
                            <!-- <input required class="form-control" type="text" name="card_type" placeholder="Debit or Credit"> -->

                            <select required class="dropdown-checkout" name="card_type">
                                <option value="" disabled selected>Debit or Credit</option>
                                <option value="Debit">Debit</option>
                                <option value="Credit">Credit</option>
                            </select>

                        </div>

                        <div class="form-field-for-payment">
							<input required class="form-control" type="text" name="name_on_card" placeholder="Name on card">
                        </div>

                        <div class="form-field-for-payment">
							<input required class="form-control" type="text" name="card_number" placeholder="Card number">
                        </div>

						<div class="form-field-for-payment">
							<input required class="form-control" type="text" name="expiration_date" placeholder="Expiration date (Ex: 0628)" maxlength="4">
                        </div>

						<div class="form-field-for-payment">
							<input required class="form-control" type="text" name="cvc_number" placeholder="The 3-digit security code" maxlength="3">
                        </div>

                    </div>

                    <div id="delivery-info">

                        <p><h4>Select Delivery Option:</h4></p>

                        <div class="form-field-for-payment">

                            <select required class="dropdown-checkout" name="delivery_option">
                                <option value="" disabled selected></option>
                                <option value="one_week_delivery">One week delivery</option>
                                <option value="two_week_delivery">Two week delivery</option>
                            </select>

                        </div>

					</div>

                    <hr>

                    <input id="form-button" class="btn btn-success btn-block" type="submit" value="Place your order">

                </form>

            </div>

            <br>

			<!-- <div class="box-element hidden" id="payment-info">
                <small>Paypal Options</small>
			</div> -->

        </div>

        <div class="col-lg-6">
            <div class="box-element-checkout">
                <a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
                {% for item in items%}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}} ({{item.product.role}})</p></div>
					<div style="flex:1"><p>${{item.product.price}}</p></div>
                    <div style="flex:1"><p>x{{item.quantity}}</p></div>
                    <div style="flex:0.8"><p>${{item.get_total}}</p></div>
				</div>
                {% endfor %}
                <h5>Items:   {{order.get_cart_items}}</h5>
				<h5>Total:   ${{order.get_cart_total}}</h5>
            </div>
        </div>


    </div>

    <script type="text/javascript">
        document.getElementById('form-button').addEventListener('click',function(e){
            submitFormData()
        })
        function submitFormData(){
            console.log('submit button clicked')


            var url = '/process_order/'
            fetch(url)
            .then(response => response.json())
            .then((data)=>{
                console.log("Order processed")
                // window.location.href = "{% url 'confirmation' %}"
            })
        }



        if (user =='AnonymousUser'){
            document.getElementById('change-info').innerHTML = ''
        }


    </script>
{% endblock content %}

webshopping/lolshopping/templates/design/confirmation.html
{% extends 'design/main.html' %}
{% load static %}
{% block content %}
    <title>Confirmation</title>
    <!-- <div style="text-align:center;">
        <h1>Thank you!</h1>
        <p>Your submission has been received.</p>
        <span id="timer"></span>
    </div>

        <script type="text/javascript">
            var count = 5;
            var redirect = "http://localhost:8000/";
            
            function countDown(){
                var timer = document.getElementById("timer");
                if(count > 0){
                    count--;
                    timer.innerHTML = "This page will redirect in "+count+" seconds.";
                    setTimeout("countDown()", 1000);
                }else{
                    window.location.href = redirect;
                }
            }
            countDown();
        </script> -->

    <div class="jumbotron text-center">
        <br>

        <h1 class="display-3">Thank You!</h1>
        <p class="lead"><strong>Your submission has been received.</strong></p>
        <hr>
        <span id="timer"></span>
        
        <p class="lead">
            <br>
            <a class="btn btn-outline-dark" href="{% url 'home' %}" role="button">Continue to homepage</a>
        </p>
        
    </div>

    <script type="text/javascript">
        var count = 10;
        var redirect = "{% url 'home' %}";
        
        function countDown(){
            var timer = document.getElementById("timer");
            if(count > 0){
                count--;
                timer.innerHTML = "This page will redirect to the home page in "+count+" seconds.";
                setTimeout("countDown()", 1000);
            }else{
                window.location.href = redirect;
            }
        }
        countDown();
    </script>

{% endblock content %}

webshopping/lolshopping/templates/design/home.html
{% extends 'design/main.html' %}
{% load static %}
{% block content %}
<title>Home</title>
    <!-- {% if request.user.is_authenticated %}

    <p>Hello, {{request.user.username}}</p>
    {% endif %} -->

<div class="filt">
    <br>
    <form method="get">

        <select class="sort-by" name="price" id="id_price" onchange='sort_filter()'>
            <option value="" selected>Sorted By:</option>
            <option value="5">5</option>
            <option value="10">10</option>
            <option value="15">15</option>
            <option value="20">20</option>
            <option value="25">25</option>
            <option value="LTH">Low to High</option>
            <option value="HTL">High to Low</option>
        </select>

        <script>
            function sort_filter() {
                var prices = document.getElementById("id_price").value;
                var current_parameter = location.search.substring(1);
                var url = window.location.href;
                var search_params = new URLSearchParams(current_parameter);

                if (current_parameter == ''){
                    window.location.search += '?price='+prices;
                } else if(search_params.has('price') && !(search_params.has('categories'))){
                    window.location.search = '?price='+prices;
                } else if(!(search_params.has('price'))){
                    window.location.search += '&price='+prices;
                } else{
                    cat = search_params.get('categories')
                    window.location.search = '?categories='+cat+'&'+cat+'='+search_params.get(cat)+'&price='+prices;
                }
            }
        </script>

    </form>

</div>

    <div class="row" id="results">

        {% for champs in all %}
        <div class="col-lg-3 abc" id="contain">
            <img class ="thumbnail" src="{{champs.imageURL}}">
            <div class="box-element product">
            <span class="champ_name">
                <h6>{{champs.name}}</h6></span>
            <span class= "champ_role">
                <h6>{{champs.role}}</h6></span>
                <hr>
                <button data-product="{{champs.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart buynow">Add to Cart</button>
                <h4 style="float: right">${{champs.price}}</h4>

            </div>
        </div>
        {% endfor %}

    </div>
<!-- <script> function myFun(){alert("item had successfully added to cart");}</script> -->
<script>
    $(".buynow").click(function(){

        var $this = $(this);
        $this.toggleClass('.buynow2');
        if($this.hasClass('.buynow')){
            $this.text('Add to Cart');
        }else{
            $this.text('Purchased')
        }

    });
</script>
{% endblock content %}

webshopping/lolshopping/templates/design/userProfile.html
{% extends 'design/main.html' %}
{% load static %}
{% block content %}

<div class ="row">
    <div class="col-md-9">
        {% if messages %}
            {% for message in messages %}
            <div class = "alert alert-{{message.tags}}">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        <div class="card card-body">

            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <p><h4>Enter Personal Information:</h4></p>
                <div>
                    <h6>Full Name: {{form.full_name}}</h6>
                    <h6>Phone: {{form.phone_number}}</h6>
                </div>
                <p><h4>Shipping Address:</h4></p>
                <div>
                    <h6>Address_line_1: {{form.address_line_1}}</h6>
                    <h6>Address_line_2: {{form.address_line_2}}</h6>
                    <h6>City: {{form.city}}</h6>
                    <h6>State: {{form.state}}</h6>
                    <h6>Postal Code: {{form.postal_code}}</h6>
                </div>

            <input class="btn btn-primary" type="submit" name="Update Information">
            </form>
        </div>
    </div>
</div>




{% endblock content %}